### ISSUE TITLE
Authorship--add developer names?

### ISSUE THREAD

**Issue by saraannwylie** [edgi-govdata-archiving/ECHO-Sunrise#17]
Rather than just this "The notebook was collaboratively authored by EDGI following our authorship protocol: https://docs.google.com/document/d/1CtDN5ZZ4Zv70fHiBTmWkDJ9mswEipX6eCYrwicP66Xw/" should we name the notebook developers or their github handles?

**Comment by ericnost** [comment]
Great question. What the web monitoring team has done is something like this:

Contributions | Name
-- | --
🔢 | Chris Amoss
🔢 📋 🤔 | Maya Anjur-Dietrich
🔢 | Marcy Beck
....

on the Github repo rather than the product itself. The emojis correspond to web monitoring analysis, team coordination, and project conceptualization. I'm aware that even though Steve, Maalvika, Kelsey and I have led the coding, this has been a group and partner-informed product.
