### ISSUE TITLE
Add program by # of facilities breakdown 

### ISSUE THREAD

**Issue by mraisle** [edgi-govdata-archiving/ECHO-Sunrise#22]
Between steps 3-4 in the current notebook, it would be great if we could show a count of how many facilities have data in each program. That might help people who don't have much direction make an initial choice about what program to run.

**Comment by ericnost** [comment]
That's a great idea! Unfortunately, there is a bit of a chicken/egg problem. We can't know how many facilities have data in the program until we go get the program data...But if we were to go get ALL ~9 data sets so that we could show this info upfront, it would take a very long time.

We CAN say how many facilities are regulated under CAA, CWA, RCRA, and report to GHGRP before the program data selection. We just can't say X facilities have CAA violations, Y have CWA inspections, etc.

**Comment by mraisle** [comment]
Gotcha. I think that's a good compromise! it gives someone at least a bit more info before they think about selecting a program.

**Comment by ericnost** [comment]
Fixed by #25
